apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-world-cron-job
spec:
  schedule: "*/1 * * * *" # at every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure